export const GOODS_DISPLAY_TYPE = {
  CARD_LIST: Symbol(),
  TABLE: Symbol(),
};

export const POS_TAB_TYPE = {
  SALE: 'SALE',
  ALLOCATEANDTRANSFER: 'ALLOCATEANDTRANSFER',
  RETURNSALE: 'RETURNSALE',
  MILKPOWDER: 2,
  WHOLESALE: 'WHOLESALE',
};


export const DOMAIN = 'http://192.168.1.225:8086';


