export const GOODS_DISPLAY_TYPE = {
  CARD_LIST: Symbol(),
  TABLE: Symbol(),
};

export const POS_TAB_TYPE = {
  SALE: 'SALE',
  ALLOCATEANDTRANSFER: 'ALLOCATEANDTRANSFER',
  RETURNSALE: 'RETURNSALE',
  MILKPOWDER: 'MILKPOWDER',
  WHOLESALE: 'WHOLESALE',
};
